"""Integration tests: verify cybir math against original code snapshots.

These tests load JSON fixture files generated by ``tests/generate_snapshots.py``
and verify that cybir's standalone functions produce identical results to the
original ``extended_kahler_cone.py`` implementation.

If fixtures have not been generated yet, tests skip gracefully.
"""

from __future__ import annotations

import json
import pathlib

import numpy as np
import pytest

from cybir.core.classify import classify_contraction
from cybir.core.flop import wall_cross_c2, wall_cross_intnums
from cybir.core.gv import gv_eff
from cybir.core.types import ContractionType

FIXTURES_DIR = pathlib.Path(__file__).parent / "fixtures" / "h11_2"

# Map original category strings to ContractionType
CATEGORY_MAP = {
    "asymptotic": ContractionType.ASYMPTOTIC,
    "CFT": ContractionType.CFT,
    "su(2) enhancement": ContractionType.SU2,
    "symmetric flop": ContractionType.SYMMETRIC_FLOP,
    "generic flop (I)": ContractionType.FLOP,
    "generic flop (II)": ContractionType.FLOP,
}


def load_fixtures():
    """Load all polytope fixture files."""
    fixtures = []
    if not FIXTURES_DIR.exists():
        return fixtures
    for f in sorted(FIXTURES_DIR.glob("polytope_*.json")):
        with open(f) as fp:
            data = json.load(fp)
        fixtures.append(data)
    return fixtures


def _wall_ids(fixtures):
    """Generate (polytope_id, wall_index) pairs for parametrisation."""
    pairs = []
    for data in fixtures:
        for i, _wall in enumerate(data["walls"]):
            pairs.append((data, i))
    return pairs


def _wall_id_str(pair):
    data, idx = pair
    return f"polytope_{data['polytope_id']}_wall_{idx}"


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

_ALL_FIXTURES = load_fixtures()
_ALL_WALLS = _wall_ids(_ALL_FIXTURES)


def _skip_if_no_fixtures():
    if not _ALL_FIXTURES:
        pytest.skip("Snapshot fixtures not generated -- run tests/generate_snapshots.py")


# ---------------------------------------------------------------------------
# Wall-crossing tests
# ---------------------------------------------------------------------------


class TestWallCrossing:
    """Verify wall_cross_intnums and wall_cross_c2 against snapshots."""

    @pytest.fixture(autouse=True)
    def _check_fixtures(self):
        _skip_if_no_fixtures()

    @pytest.mark.parametrize(
        "wall_pair", _ALL_WALLS, ids=[_wall_id_str(p) for p in _ALL_WALLS]
    )
    def test_wall_crossing_matches_snapshot(self, wall_pair):
        data, idx = wall_pair
        wall = data["walls"][idx]

        # Only flop-type walls have flopped quantities
        if wall["flopped_int_nums"] is None:
            pytest.skip("No flopped data for this wall type")

        int_nums = np.array(wall["int_nums"])
        curve = np.array(wall["curve"])
        gv_eff_3 = wall["gv_eff_3"]
        gv_eff_1 = wall["gv_eff_1"]
        expected_intnums = np.array(wall["flopped_int_nums"])
        expected_c2 = np.array(wall["flopped_c2"])

        # Test intersection number wall-crossing
        result_intnums = wall_cross_intnums(int_nums, curve, gv_eff_3)
        np.testing.assert_allclose(
            result_intnums,
            expected_intnums,
            atol=1e-10,
            err_msg=f"wall_cross_intnums mismatch for polytope "
            f"{data['polytope_id']} wall {idx}",
        )

        # Test c2 wall-crossing
        c2 = np.array(wall["c2"])
        result_c2 = wall_cross_c2(c2, curve, gv_eff_1)
        np.testing.assert_allclose(
            result_c2,
            expected_c2,
            atol=1e-10,
            err_msg=f"wall_cross_c2 mismatch for polytope "
            f"{data['polytope_id']} wall {idx}",
        )


# ---------------------------------------------------------------------------
# GV effective invariant tests
# ---------------------------------------------------------------------------


class TestGVEffective:
    """Verify gv_eff against snapshots."""

    @pytest.fixture(autouse=True)
    def _check_fixtures(self):
        _skip_if_no_fixtures()

    @pytest.mark.parametrize(
        "wall_pair", _ALL_WALLS, ids=[_wall_id_str(p) for p in _ALL_WALLS]
    )
    def test_gv_eff_matches_snapshot(self, wall_pair):
        data, idx = wall_pair
        wall = data["walls"][idx]

        if wall["gv_series"] is None:
            pytest.skip("No GV series for this wall")

        gv_series = wall["gv_series"]
        expected_eff_1 = wall["gv_eff_1"]
        expected_eff_3 = wall["gv_eff_3"]

        if expected_eff_1 is None or expected_eff_3 is None:
            pytest.skip("No effective GV data for this wall")

        result_eff_1, result_eff_3 = gv_eff(gv_series)

        assert result_eff_1 == expected_eff_1, (
            f"gv_eff_1 mismatch for polytope {data['polytope_id']} wall {idx}: "
            f"got {result_eff_1}, expected {expected_eff_1}"
        )
        assert result_eff_3 == expected_eff_3, (
            f"gv_eff_3 mismatch for polytope {data['polytope_id']} wall {idx}: "
            f"got {result_eff_3}, expected {expected_eff_3}"
        )


# ---------------------------------------------------------------------------
# Classification tests
# ---------------------------------------------------------------------------


class TestClassification:
    """Verify classify_contraction against snapshots."""

    @pytest.fixture(autouse=True)
    def _check_fixtures(self):
        _skip_if_no_fixtures()

    @pytest.mark.parametrize(
        "wall_pair", _ALL_WALLS, ids=[_wall_id_str(p) for p in _ALL_WALLS]
    )
    def test_classification_matches_snapshot(self, wall_pair):
        data, idx = wall_pair
        wall = data["walls"][idx]

        original_category = wall["contraction_type"]

        # Skip potent walls (the original code doesn't classify these
        # as one of the 5 standard types)
        if "potent" in original_category.lower() or "insufficient" in original_category.lower():
            pytest.skip(f"Potent/insufficient wall: {original_category}")

        expected_type = CATEGORY_MAP.get(original_category)
        if expected_type is None:
            pytest.skip(f"Unknown original category: {original_category}")

        int_nums = np.array(wall["int_nums"])
        c2 = np.array(wall["c2"])
        curve = np.array(wall["curve"])

        # For asymptotic/CFT walls, gv_series may be None -- classify_contraction
        # handles these before touching gv_series.
        gv_series = wall["gv_series"] if wall["gv_series"] is not None else []

        # Asymptotic and CFT don't need gv_series
        if expected_type in (ContractionType.ASYMPTOTIC, ContractionType.CFT):
            # Use a dummy gv_series since classify checks asymptotic/CFT first
            gv_series = [1, 0]

        result = classify_contraction(int_nums, c2, curve, gv_series)
        result_type = result["contraction_type"]

        assert result_type == expected_type, (
            f"Classification mismatch for polytope {data['polytope_id']} "
            f"wall {idx}: got {result_type.name}, expected {expected_type.name} "
            f"(original: {original_category})"
        )
