"""Toric curve enumeration, FRST detection, and classification.

Provides tools for computing toric curves from 2-face triangulations of
the polytope, classifying phases as FRST/vex/non-inherited, and
diagnosing toric curves as flop/Weyl/other based on normal bundles
and enveloping divisor positions.

The toric curves of a CY3 hypersurface in a toric variety provide an
**inner bound** on the Mori cone: every toric curve is a genuine curve
class, so the cone generated by toric curves is contained in the
full Mori cone. Combined with the outer bound from ``mori_cone_cap``,
this can pin down the exact Mori cone for many phases.

Ported from cornell-dev:
- ``lib/geom/curves/toric.py`` (``compute_toric_curves_old``)
- ``lib_axion/cytools_ext/polytopeface_ext.py``
  (``induced_2face_triangulations_old``)

References
----------
.. [1] N. Gendler, N. Heidenreich, L. McAllister, J. Moritz, T. Rudelius,
   arXiv:2212.10573, "Counting Calabi-Yau Threefolds" (Section 3.2).

.. [2] M. Demirtas, M. Kim, L. McAllister, J. Moritz, A. Rios-Tascon,
   arXiv:2303.00757, "Computational Mirror Symmetry".
"""

import itertools
from dataclasses import dataclass, field

import numpy as np


@dataclass
class ToricCurveData:
    """Container for toric curve computation results.

    Holds classified toric curves and their GV invariants, organized
    by category (flop, Weyl genus-0, Weyl higher-genus, other,
    and 1-face minimal edges).

    Attributes
    ----------
    flop_curves : list of numpy.ndarray
        Curves classified as flop-type (normal bundle (-1,-1)).
    weyl_curves_g0 : list of numpy.ndarray
        Weyl-type curves at genus 0.
    weyl_curves_higher_genus : list of numpy.ndarray
        Weyl-type curves at higher genus.
    other_curves : list of numpy.ndarray
        Curves not fitting flop or Weyl categories.
    minface1_curves : list of numpy.ndarray
        Curves from 1-face minimal edges.
    gv_dict : dict
        Map from curve tuple -> toric GV invariant.
    """

    flop_curves: list = field(default_factory=list)
    weyl_curves_g0: list = field(default_factory=list)
    weyl_curves_higher_genus: list = field(default_factory=list)
    other_curves: list = field(default_factory=list)
    minface1_curves: list = field(default_factory=list)
    gv_dict: dict = field(default_factory=dict)

    def merge(self, other):
        """Merge another ToricCurveData into this one (in place).

        Parameters
        ----------
        other : ToricCurveData
            Data to merge into this instance.
        """
        self.flop_curves.extend(other.flop_curves)
        self.weyl_curves_g0.extend(other.weyl_curves_g0)
        self.weyl_curves_higher_genus.extend(other.weyl_curves_higher_genus)
        self.other_curves.extend(other.other_curves)
        self.minface1_curves.extend(other.minface1_curves)
        self.gv_dict.update(other.gv_dict)

    def all_curves(self):
        """Return all curves as a flat list.

        Returns
        -------
        list of numpy.ndarray
            All curves across all categories.
        """
        return (
            self.flop_curves
            + self.weyl_curves_g0
            + self.weyl_curves_higher_genus
            + self.other_curves
            + self.minface1_curves
        )


def induced_2face_triangulations(polytope, triangulations):
    """Compute induced 2-face triangulations from a list of FRSTs.

    For each full triangulation, extracts the induced triangulation on
    each 2-face of the polytope. Deduplicates at the 2-face level
    using frozenset comparison.

    Parameters
    ----------
    polytope : cytools.Polytope
        The polytope.
    triangulations : list
        List of CYTools Triangulation objects (FRSTs).

    Returns
    -------
    list of list of numpy.ndarray
        For each 2-face, a list of distinct induced triangulations.
        Each triangulation is an array of 3-simplices (triangles),
        where point indices include the origin (index 0).

    Notes
    -----
    Ported from cornell-dev ``induced_2face_triangulations_old`` in
    ``lib_axion/cytools_ext/polytopeface_ext.py``.

    The algorithm:

    1. Get 2-faces via ``polytope.faces(2)``.
    2. For each full triangulation, extract 4-simplices, drop the
       origin (index 0) to get 3-element subsets.
    3. Extract all 3-subsets (combinations of 3) from each 4-simplex.
    4. Assign each 3-subset to the 2-face containing all 3 points.
    5. Keep only simplices assigned to exactly one 2-face.
    6. Deduplicate using frozenset of sorted simplex tuples.
    """
    twofaces = [set(f.points(as_indices=True)) for f in polytope.faces(2)]
    triangulations_2faces = [[] for _ in twofaces]

    for t in triangulations:
        # Get 4-simplices, drop origin (row index 0)
        four_simplices = np.delete(t.simplices().T, 0, 0).T
        # Extract all 3-subsets
        three_simplices = [
            [x for x in itertools.combinations(s, 3)] for s in four_simplices
        ]
        three_simplices = {
            tuple(item) for sublist in three_simplices for item in sublist
        }
        three_simplices = [set(s) for s in three_simplices]

        # Assign each 3-simplex to 2-faces
        twoface_assignments0 = [
            np.where([len(s.intersection(f)) == 3 for f in twofaces])[0]
            for s in three_simplices
        ]
        # Keep only simplices assigned to exactly one 2-face
        twoface_simps_pos = np.where(
            [len(i) == 1 for i in twoface_assignments0]
        )[0]
        twoface_assignments = np.array(
            [twoface_assignments0[i][0] for i in twoface_simps_pos]
        )
        two_face_simps = np.array(three_simplices, dtype=object)[
            twoface_simps_pos
        ]
        two_face_simps = np.array([np.sort(list(s)) for s in two_face_simps])
        induced_two_face_triag = [
            two_face_simps[np.where(i == twoface_assignments)[0]]
            for i in range(len(twofaces))
        ]

        for i in range(len(twofaces)):
            triangulations_2faces[i].append(induced_two_face_triag[i])

    # Deduplicate per 2-face
    induced_two_face_triag_set = [
        {frozenset(tuple(k) for k in j) for j in i}
        for i in triangulations_2faces
    ]
    triangulations_2faces = [
        [np.array(list(j)) for j in list(i)]
        for i in induced_two_face_triag_set
    ]

    return triangulations_2faces


def classify_phase_type(kahler_cone, charge_matrix, moving_cone_obj=None):
    """Classify a phase as FRST, vex, or non-inherited.

    Uses the FRST detection trichotomy (D-06):

    1. Compute the moving cone from the charge matrix.
    2. Check if the phase's Kahler cone has solid intersection with
       the moving cone.
    3. If solid, find an interior point, lift to a height vector,
       and use regfans to subdivide the vector configuration.
    4. Check if the resulting fan respects the point configuration
       (i.e., is a fine regular star triangulation).

    Parameters
    ----------
    kahler_cone : cytools.Cone
        The phase's Kahler cone.
    charge_matrix : numpy.ndarray
        GLSM charge matrix Q, shape ``(h11, n_points)``.
    moving_cone_obj : cytools.Cone, optional
        Pre-computed moving cone. If None, computed from charge_matrix.

    Returns
    -------
    tuple of (str, object)
        ``(phase_type, fan_or_none)`` where ``phase_type`` is
        ``'frst'``, ``'vex'``, or ``'non_inherited'``, and
        ``fan_or_none`` is the regfans Fan for frst/vex phases
        or None.

    Notes
    -----
    Per D-06 in CONTEXT.md. Uses regfans ``VectorConfiguration`` for
    FRST detection. Uses CYTools ``Cone.intersection()`` and
    ``Cone.is_solid()`` for checking solid intersection with the
    moving cone (both methods verified to exist on the CYTools
    Cone class).
    """
    from regfans import VectorConfiguration

    from .util import moving_cone

    if moving_cone_obj is None:
        moving_cone_obj = moving_cone(charge_matrix)

    # Check solid intersection with moving cone
    try:
        intersection = kahler_cone.intersection(moving_cone_obj)
        if not intersection.is_solid():
            return ("non_inherited", None)

        # Find interior point and lift to heights
        J = intersection.tip_of_stretched_cone(1)
    except Exception:
        return ("non_inherited", None)

    # Lift to height vector: solve Qx = J (least squares)
    Q = np.asarray(charge_matrix, dtype=float)
    h = np.linalg.lstsq(Q, J.astype(float), rcond=None)[0]

    # Subdivide vector configuration
    vc = VectorConfiguration(Q.T)
    try:
        fan = vc.triangulate(heights=h)
    except Exception:
        return ("non_inherited", None)

    if fan.respects_ptconfig():
        return ("frst", fan)
    else:
        return ("vex", fan)


def orient_curves_for_phase(curves, tip):
    """Re-orient toric curves for a specific phase.

    Each curve is oriented so that ``tip @ curve > 0``. Curves
    orthogonal to ``tip`` are left unchanged.

    Parameters
    ----------
    curves : list of numpy.ndarray
        Curves in canonical orientation.
    tip : numpy.ndarray
        Interior point of the phase's Kahler cone.

    Returns
    -------
    list of numpy.ndarray
        Re-oriented curves.

    Notes
    -----
    Per D-10 in CONTEXT.md. Toric curves are stored with canonical
    orientation (first nonzero entry positive). To use them in a
    specific phase, they must be re-oriented so that the Kahler
    form evaluates positively on them.
    """
    oriented = []
    for c in curves:
        sign = np.sign(tip @ c)
        if sign == 0:
            oriented.append(c)
        else:
            oriented.append(int(sign) * c)
    return oriented


def compute_toric_curves(cy, face_triangulations, tip=None):
    """Compute toric curves from induced 2-face triangulations.

    Enumerates edges in the 2-face triangulations, computes their
    charge vectors in the GLSM basis, classifies by normal bundle
    and enveloping divisor position, and diagnoses as flop/Weyl/other.

    Parameters
    ----------
    cy : cytools.CalabiYau
        The Calabi-Yau threefold.
    face_triangulations : list of list of numpy.ndarray
        Induced 2-face triangulations (from
        :func:`induced_2face_triangulations`).
    tip : numpy.ndarray, optional
        Interior point of the Kahler cone for orientation.
        If None, computed from ``cy.toric_kahler_cone()``.

    Returns
    -------
    ToricCurveData
        Classified toric curves with GV invariants.

    Notes
    -----
    Ported from cornell-dev ``compute_toric_curves_old`` in
    ``lib/geom/curves/toric.py``.

    **CRITICAL**: Uses ``intersection_numbers(in_basis=False)`` for
    raw point indices. Using ``in_basis=True`` would give incorrect
    charge vectors.

    The algorithm per 2-face and triangulation:

    1. Find all edges (pairs of points) in simplices.
    2. Classify edges as "twoface" (shared by 2 triangles) or
       "oneface" (in 1 triangle, boundary edges).
    3. For twoface edges, find the "relevant quad" (the 4 points
       of the two triangles sharing the edge) and compute double
       intersection numbers from the polytope geometry.
    4. Compute normal bundles (reversed double intersection numbers).
    5. Find enveloping divisors (endpoint with max normal bundle).
    6. Build a local intersection number dictionary for charge
       computation.
    7. Compute charge vectors in the GLSM basis.
    8. Orient curves using the Kahler cone tip.
    9. Classify by enveloping divisor position:
       - Vertex envelope -> flop (GV = n_component)
       - 1-face interior -> flop if (-1,-1), else Weyl (genus-based)
       - 2-face interior -> GV from normal bundle, classify by max

    References
    ----------
    .. [1] arXiv:2212.10573, Section 3.2 for the role of toric curves
       as inner bounds on the Mori cone.
    """
    p = cy.polytope()

    # Intersection numbers with RAW point indices -- CRITICAL
    intnums_raw = cy.intersection_numbers(in_basis=False)

    # Kahler cone tip for orientation
    if tip is None:
        toric_K = cy.toric_kahler_cone()
        tip = toric_K.tip_of_stretched_cone(1)

    # Polytope data
    pts = p.points()
    basis = p.glsm_basis()
    twofaces = p.faces(2)
    # Face genera from dual polytope
    twoface_genera = np.array(
        [len(f.interior_points()) for f in p.dual().faces(1)]
    )
    oneface_genera = np.array(
        [len(f.interior_points()) for f in p.dual().faces(2)]
    )

    # Output accumulators
    gv_dict_all = {}
    all_flop_curves = set()
    all_weyl_g0 = set()
    all_weyl_higher = set()
    all_other = set()
    all_minface1 = set()

    for face_index in range(len(face_triangulations)):
        two_face = twofaces[face_index]
        n_two_face_component = twoface_genera[face_index] + 1

        # Interior points of sub-faces of this 2-face
        points_interior_to_one_faces = []
        for f in two_face.faces(1):
            for i in f.interior_points(as_indices=True):
                points_interior_to_one_faces.append(i)
        points_interior_to_one_faces = np.array(points_interior_to_one_faces)

        points_interior_to_two_faces = []
        for f in two_face.faces(2):
            for i in f.interior_points(as_indices=True):
                points_interior_to_two_faces.append(i)
        points_interior_to_two_faces = np.array(points_interior_to_two_faces)

        vertices = []
        for f in two_face.faces(0):
            for i in f.interior_points(as_indices=True):
                vertices.append(i)
        vertices = np.array(vertices)

        for triangulation_index in range(
            len(face_triangulations[face_index])
        ):
            two_face_triag = face_triangulations[face_index][
                triangulation_index
            ]

            # Find all edges (pairs of points in simplices)
            curves = [
                [x for x in itertools.combinations(t, 2)]
                for t in two_face_triag
            ]
            curves = [cc for c in curves for cc in c]
            curves = set(curves)
            curves = [c for c in curves]
            simps_set = [set(t) for t in two_face_triag]

            # Classify edges by how many simplices contain them
            twoface_curves_pos = np.where(
                [
                    len(
                        np.where(
                            [set(c).issubset(s) for s in simps_set]
                        )[0]
                    )
                    == 2
                    for c in curves
                ]
            )[0]
            oneface_curves_pos = np.where(
                [
                    len(
                        np.where(
                            [set(c).issubset(s) for s in simps_set]
                        )[0]
                    )
                    == 1
                    for c in curves
                ]
            )[0]
            twoface_curves = np.array(curves, dtype=object)[
                twoface_curves_pos
            ]
            oneface_curves = np.array(curves, dtype=object)[
                oneface_curves_pos
            ]

            # Find relevant quads for twoface curves
            relevant_quads = [
                set(
                    two_face_triag[
                        np.where(
                            [set(c).issubset(s) for s in simps_set]
                        )[0]
                    ].flatten()
                )
                for c in twoface_curves
            ]
            for i in range(len(relevant_quads)):
                relevant_quads[i].remove(twoface_curves[i][0])
                relevant_quads[i].remove(twoface_curves[i][1])
            relevant_quads = [list(q) for q in relevant_quads]

            # Compute double intersection numbers
            double_intnums = np.zeros((len(twoface_curves), 2)).astype(int)
            for curve_index in range(len(twoface_curves)):
                for doubling_index in range(2):
                    three_points = [
                        pts[relevant_quads[curve_index][0]]
                        - pts[twoface_curves[curve_index][1 - doubling_index]],
                        pts[relevant_quads[curve_index][1]]
                        - pts[twoface_curves[curve_index][1 - doubling_index]],
                        pts[twoface_curves[curve_index][doubling_index]]
                        - pts[twoface_curves[curve_index][1 - doubling_index]],
                    ]
                    oneone_point = three_points[0] + three_points[1]
                    nonzero_pos = np.where(oneone_point != 0)[0]
                    if len(nonzero_pos) == 0:
                        double_intnums[curve_index][doubling_index] = 0
                    else:
                        double_intnums[curve_index][doubling_index] = (
                            -oneone_point[nonzero_pos[0]]
                            / three_points[2][nonzero_pos[0]]
                        )

            # Normal bundles (reversed order of double intersection numbers)
            normal_bundles = np.array(
                [np.transpose(double_intnums)[1], np.transpose(double_intnums)[0]]
            ).T
            if len(twoface_curves) == 0:
                # Only 1-face curves
                oneface_charges = np.array(
                    [
                        [
                            intnums_raw.get(tuple(np.sort([c[0], c[1], i])), 0)
                            for i in basis
                        ]
                        for c in oneface_curves
                    ]
                )
                for ch in oneface_charges:
                    all_minface1.add(tuple(ch))
                continue

            enveloping_divisors_pos = np.array(
                [np.where(max(n) == n)[0][0] for n in normal_bundles]
            )
            enveloping_divisors = np.array(
                [
                    twoface_curves[i][enveloping_divisors_pos[i]]
                    for i in range(len(enveloping_divisors_pos))
                ]
            )

            # Determine envelope positions
            vertex_envelope_pos = np.where(
                np.array(
                    [
                        len(np.where(vertices == d)[0]) > 0
                        for d in enveloping_divisors
                    ]
                )
            )[0]
            one_face_envelope_pos = np.where(
                np.array(
                    [
                        len(
                            np.where(
                                points_interior_to_one_faces == d
                            )[0]
                        )
                        > 0
                        for d in enveloping_divisors
                    ]
                )
            )[0]
            two_face_envelope_pos = np.where(
                np.array(
                    [
                        len(
                            np.where(
                                points_interior_to_two_faces == d
                            )[0]
                        )
                        > 0
                        for d in enveloping_divisors
                    ]
                )
            )[0]

            # Build local intersection number dictionary
            triplets0 = [
                tuple(np.sort([c[0], c[0], c[1]])) for c in twoface_curves
            ]
            triplets1 = [
                tuple(np.sort([c[0], c[1], c[1]])) for c in twoface_curves
            ]
            double_int_dict0 = {
                triplets0[i]: (
                    (1 + twoface_genera[face_index]) * double_intnums[i][0]
                )
                for i in range(len(double_intnums))
            }
            double_int_dict1 = {
                triplets1[i]: (
                    (1 + twoface_genera[face_index]) * double_intnums[i][1]
                )
                for i in range(len(double_intnums))
            }
            double_int_dict = {**double_int_dict0, **double_int_dict1}
            triplet_int_dict = {
                tuple(np.sort(t)): (1 + twoface_genera[face_index])
                for t in two_face_triag
            }
            intnums = {**double_int_dict, **triplet_int_dict}

            # Compute charge vectors
            oneface_charges = np.array(
                [
                    [
                        intnums_raw.get(tuple(np.sort([c[0], c[1], i])), 0)
                        for i in basis
                    ]
                    for c in oneface_curves
                ]
            )
            twoface_charges = np.array(
                [
                    [
                        intnums.get(tuple(np.sort([c[0], c[1], i])), 0)
                        for i in basis
                    ]
                    for c in twoface_curves
                ]
            )
            twoface_charges_reduced = (
                twoface_charges / n_two_face_component
            ).astype(int)
            twoface_charges_reduced_birded = np.array(
                [
                    (np.sign(c @ tip).astype(int)) * c
                    for c in twoface_charges_reduced
                ]
            )

            two_face_GV = np.zeros(len(twoface_curves)).astype(int)

            # Classify by enveloping divisor position
            for i in vertex_envelope_pos:
                two_face_GV[i] = n_two_face_component
                all_flop_curves.add(tuple(twoface_charges_reduced_birded[i]))

            for i in one_face_envelope_pos:
                if np.all(normal_bundles[i] == np.array([-1, -1])):
                    two_face_GV[i] = n_two_face_component
                    all_flop_curves.add(
                        tuple(twoface_charges_reduced_birded[i])
                    )
                else:
                    genus = oneface_genera[
                        np.where(
                            [
                                len(
                                    np.where(
                                        f.interior_points(as_indices=True)
                                        == enveloping_divisors[i]
                                    )[0]
                                )
                                == 1
                                for f in p.faces(1)
                            ]
                        )[0][0]
                    ]
                    two_face_GV[i] = 2 * genus - 2
                    if genus == 0:
                        all_weyl_g0.add(
                            tuple(twoface_charges_reduced_birded[i])
                        )
                    else:
                        all_weyl_higher.add(
                            tuple(twoface_charges_reduced_birded[i])
                        )

            for i in two_face_envelope_pos:
                max_norm_b = max(normal_bundles[i])
                two_face_GV[i] = (
                    (-1) ** (max_norm_b + 1)
                    * (max_norm_b + 2)
                    * n_two_face_component
                )
                if np.all(normal_bundles[i] == np.array([-1, -1])):
                    all_flop_curves.add(
                        tuple(twoface_charges_reduced_birded[i])
                    )
                elif max_norm_b == 0:
                    all_weyl_g0.add(
                        tuple(twoface_charges_reduced_birded[i])
                    )
                elif max_norm_b > 0:
                    all_other.add(
                        tuple(twoface_charges_reduced_birded[i])
                    )

            for ch in oneface_charges:
                all_minface1.add(tuple(ch))

            # Build GV dictionary for this triangulation
            gv_dict = {
                tuple(twoface_charges_reduced_birded[i]): int(two_face_GV[i])
                for i in range(len(twoface_charges_reduced))
            }
            gv_dict_all = {**gv_dict_all, **gv_dict}

    return ToricCurveData(
        flop_curves=[np.array(c) for c in all_flop_curves],
        weyl_curves_g0=[np.array(c) for c in all_weyl_g0],
        weyl_curves_higher_genus=[np.array(c) for c in all_weyl_higher],
        other_curves=[np.array(c) for c in all_other],
        minface1_curves=[np.array(c) for c in all_minface1],
        gv_dict=gv_dict_all,
    )
